%lex
%%

\s+               /* skip whitespace */

\d+               return "Number"
\w+               return "IDENTIFIER"

/lex

%{

%}

%%

Program
  : /* empty */   { $$ = { type: "Program", body: [] } }
  ;
