export enum NodeKind {
  AdditiveExpression = 'AdditiveExpression',
  ApplyStatement = 'ApplyStatement',
  Arguments = 'Arguments',
  ArrayLiteral = 'ArrayLiteral',
  ArrowFunctionBody = 'ArrowFunctionBody',
  ArrowParameters = 'ArrowParameters',
  AsOperator = 'AsOperator',
  AssignmentExpression = 'AssignmentExpression',
  AssignmentExpression_In = 'AssignmentExpression_In',
  AssociativityExpression = 'AssociativityExpression',
  AutoescapeStatement = 'AutoescapeStatement',
  BitwiseANDExpression = 'BitwiseANDExpression',
  BitwiseANDExpression_In = 'BitwiseANDExpression_In',
  BitwiseORExpression = 'BitwiseORExpression',
  BitwiseORExpression_In = 'BitwiseORExpression_In',
  BitwiseXORExpression = 'BitwiseXORExpression',
  BitwiseXORExpression_In = 'BitwiseXORExpression_In',
  BlockInlineStatement = 'BlockInlineStatement',
  BlockStatement = 'BlockStatement',
  BooleanLiteral = 'BooleanLiteral',
  BoxMemberExpression = 'BoxMemberExpression',
  CacheStatement = 'CacheStatement',
  CallExpression = 'CallExpression',
  CoalesceExpression = 'CoalesceExpression',
  CoalesceExpression_In = 'CoalesceExpression_In',
  Comment = 'Comment',
  ConcatExpression = 'ConcatExpression',
  ConditionalExpression = 'ConditionalExpression',
  ConditionalExpression_In = 'ConditionalExpression_In',
  DeprecatedStatement = 'DeprecatedStatement',
  DoStatement = 'DoStatement',
  DotMemberExpression = 'DotMemberExpression',
  EmbedStatement = 'EmbedStatement',
  EqualityExpression = 'EqualityExpression',
  EqualityExpression_In = 'EqualityExpression_In',
  ExponentiationExpression = 'ExponentiationExpression',
  Expression = 'Expression',
  ExpressionList = 'ExpressionList',
  ExpressionList_In = 'ExpressionList_In',
  Expression_In = 'Expression_In',
  ExtendsStatement = 'ExtendsStatement',
  Filter = 'Filter',
  FilterExpression = 'FilterExpression',
  FilterExpression_In = 'FilterExpression_In',
  FlushStatement = 'FlushStatement',
  ForInStatement = 'ForInStatement',
  FormThemeStatement = 'FormThemeStatement',
  FromStatement = 'FromStatement',
  Identifier = 'Identifier',
  IfStatement = 'IfStatement',
  ImportStatement = 'ImportStatement',
  IncludeStatement = 'IncludeStatement',
  LeftHandSideExpression = 'LeftHandSideExpression',
  Literal = 'Literal',
  LogicalANDExpression = 'LogicalANDExpression',
  LogicalANDExpression_In = 'LogicalANDExpression_In',
  LogicalORExpression = 'LogicalORExpression',
  LogicalORExpression_In = 'LogicalORExpression_In',
  MacroStatement = 'MacroStatement',
  MemberExpression = 'MemberExpression',
  MultiplicativeExpression = 'MultiplicativeExpression',
  Node = 'Node',
  NullLiteral = 'NullLiteral',
  NumericLiteral = 'NumericLiteral',
  ObjectLiteral = 'ObjectLiteral',
  ParenthesizedExpression = 'ParenthesizedExpression',
  PrimaryExpression = 'PrimaryExpression',
  PropertyDefinition = 'PropertyDefinition',
  PropertyName = 'PropertyName',
  RangeExpression = 'RangeExpression',
  RelationalExpression = 'RelationalExpression',
  RelationalExpression_In = 'RelationalExpression_In',
  SandboxStatement = 'SandboxStatement',
  SetBlockStatement = 'SetBlockStatement',
  SetInlineStatement = 'SetInlineStatement',
  SingleParamArrowFunction = 'SingleParamArrowFunction',
  SourceElement = 'SourceElement',
  SourceElementList = 'SourceElementList',
  Statement = 'Statement',
  StopwatchStatement = 'StopwatchStatement',
  StringInterpolation = 'StringInterpolation',
  StringLiteral = 'StringLiteral',
  Template = 'Template',
  Text = 'Text',
  TransDefaultDomainStatement = 'TransDefaultDomainStatement',
  TransStatement = 'TransStatement',
  UnaryExpression = 'UnaryExpression',
  UpdateExpression = 'UpdateExpression',
  UseStatement = 'UseStatement',
  VariableDeclaration = 'VariableDeclaration',
  VariableDeclarationList = 'VariableDeclarationList',
  VariableStatement = 'VariableStatement',
  VerbatimStatement = 'VerbatimStatement',
  WithStatement = 'WithStatement',
}

export interface Node {
  type: NodeKind;
}

export interface Identifier extends Node {
  type: NodeKind.Identifier;
  value: string;
}
